### ISSUE TITLE
Errors being thrown - Compatibility script failure ?

### ISSUE THREAD

**Issue by wrighty43** [sonos/sonos-audioclip-tts#1]
I am seeing the following errors when trying to use this code for a proof of concept demo.  JS isn't my normal language so please advise on the troubleshooting items.  Household are pulling through correctly.
![image](https://user-images.githubusercontent.com/2223814/55013279-b6397c00-4fe0-11e9-820d-b3c971fe657d.png)

**Comment by mattwelch** [comment]
Good catch. The code needed to be updated to reflect the new AUDIO_CLIP capability flag. You must have nothing but newer players in your household, and since we were looking for NOT AUDIO_CLIP before, you weren't getting any players. The error you saw is the result of two bugs:

1. The above mentioned AUDIO_CLIP update, which is now merged
2. A separate bug around handling of empty audio clip capable responses. We'll get that fixed soon.

**Comment by wrighty43** [comment]
Thanks I am dealing with your SONOS UK Installed Solutions Business Development Manager in the UK so the two speakers were demo units from yourselves for a project I am looking into.
